spring.application.name=product-service
spring.data.mongodb.uri=mongodb://root:root@mongodb:27017/product-service?authSource=admin
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
server.port=0
# Enable tracing
management.tracing.enabled=true

# Send traces to Zipkin (if using Zipkin)
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Expose Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,traces